### ISSUE TITLE
Wolfteam MF - PC-98 compatibility

### ISSUE THREAD

**Issue by mistydemeo** [ValleyBell/MidiConverters#17]
I've been testing Wolfteam ripping music from Wolfteam PC-98 games, and noticed that while some games work fine, others produce garbled MIDIs and `wtmf2mid` reports a number of errors. I'm not 100% sure if this is my fault, for ripping the MF files incorrectly, or if it's expected that newer PC-98 games don't work yet. I saw a mention of `MU` headers in the code and in bb342040d0e799ac8bfd9db62906da45c4a31055, but I'm not sure if I should be searching for/ripping those. Is that for FM?

Here's the compatibility list of what I've tested; I only tested games with MT-32 MIDI soundtracks, so there are some games in this window I'm missing.

Successful:

D: Oushuu Shinkirou
Diamond Players
Span of Dream
Zan - Yasha Enbukyou

Unsuccessful:

Arcus III
Gulf War Soukouden
Hiouden
Hiouden II
Shinsengumi - Bakumatsu Genshikou
Suzaku
Tenbu Limited
Zan II

**Comment by ValleyBell** [comment]
Those games all worked just fine for me. see [Arcus_3__111_MI01.zip](https://github.com/ValleyBell/MidiConverters/files/14739917/Arcus_3__111_MI01.zip)

Did you rip the songs from the original game? If so, maybe the decompression went wrong.  
I was lazy and just took the files from the Hoot packages (i.e. `arcus398.zip`), because those are usually not compressed.

The `MU` header should be for FM songs, yeah. However the format is exactly the same, so I thought I could support converting those as well.

**Comment by mistydemeo** [comment]
Sorry I didn't reply sooner! I didn't even think of trying Hoot, but that confirms it's my fault: I ripped them badly from the floppies, and the Hoot versions work.
